name: Deploy Gatsby site to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때마다 실행

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Ubuntu 환경에서 실행
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 저장소 코드 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Node.js 버전 설정 (Gatsby 호환 버전)

      - name: Install dependencies
        run: |
          npm install
          npm install gatsby-transformer-sharp gatsby-plugin-sharp gatsby-remark-images gatsby-remark-responsive-iframe gatsby-remark-prismjs gatsby-remark-copy-linked-files gatsby-remark-smartypants gatsby-plugin-react-helmet

      - name: Build Gatsby site
        run: npm run build # Gatsby 사이트 빌드

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 